network_name: dev
path: test/dev

emulated_code:
  name: camb
  version: "1.5.0"
  inputs: [ ombh2, omch2, As, ns, H0, tau ]
  extra_args:
    lens_potential_accuracy: 1

samples:
  Ntraining: 100
  
  parameters:
    # Sampled parameters
    ombh2: [0.01,0.05]
    omch2: [0.05,0.50]
    logA: [2.0,4.0]
    tau: [0.02,0.12]
    ns: [0.8,1.2]
    h: [0.4,1.0]
    # Derived parameters
    As: "lambda logA: 1.e-10 * np.exp(logA)"
    H0: "lambda h: h * 100.0"
    # Computed parameters
    thetastar:
    sigma8:
    YHe:
    zrei:
    taurend:
    zstar:
    rstar:
    zdrag:
    N_eff:

networks:
  - quantity: derived
    type: NN
    training:
      validation_split: 0.1
      learning_rates: [ 1.e-2, 1.e-4, 1.e-6 ]
      batch_sizes: [ 1000, 1000, 1000 ]
      gradient_accumulation_steps: [ 1, 1, 1 ]
      patience_values: [ 25, 25, 25 ]
      max_epochs: [ 1000, 1000, 1000 ]

  - quantity: Cl/tt
    type: NN
    log: True
    modes:
      label: l
      range: [2,2508]
    n_traits:
      n_hidden: [ 512, 512, 512, 512 ]
    training:
      validation_split: 0.1
      learning_rates: [ 1.e-2, 1.e-4, 1.e-6 ]
      batch_sizes: [ 1000, 1000, 1000 ]
      gradient_accumulation_steps: [ 1, 1, 1 ]
      patience_values: [ 25, 25, 25 ]
      max_epochs: [ 1000, 1000, 1000 ]

  - quantity: Cl/pp
    inputs: [ ombh2, omch2, logA, ns, h ]
    type: NN
    log: True
    modes:
      label: l
      range: [2,2508]
    n_traits:
      n_hidden: [ 512, 512, 512, 512 ]
    training:
      validation_split: 0.1
      learning_rates: [ 1.e-2, 1.e-4, 1.e-6 ]
      batch_sizes: [ 1000, 1000, 1000 ]
      gradient_accumulation_steps: [ 1, 1, 1 ]
      patience_values: [ 25, 25, 25 ]
      max_epochs: [ 1000, 1000, 1000 ]

  - quantity: Hubble
    type: NN
    modes:
      label: z
      range: [0,20]
      steps: 200
    n_traits:
      n_hidden: [ 512, 512, 512, 512 ]
    training:
      validation_split: 0.1
      learning_rates: [ 1.e-2, 1.e-4, 1.e-6 ]
      batch_sizes: [ 1000, 1000, 1000 ]
      gradient_accumulation_steps: [ 1, 1, 1 ]
      patience_values: [ 25, 25, 25 ]
      max_epochs: [ 1000, 1000, 1000 ]

  - quantity: sigma8
    type: NN
    modes:
      label: z
      range: [0,20]
      steps: 200
    n_traits:
      n_hidden: [ 512, 512, 512, 512 ]
    training:
      validation_split: 0.1
      learning_rates: [ 1.e-2, 1.e-4, 1.e-6 ]
      batch_sizes: [ 1000, 1000, 1000 ]
      gradient_accumulation_steps: [ 1, 1, 1 ]
      patience_values: [ 25, 25, 25 ]
      max_epochs: [ 1000, 1000, 1000 ]

  - quantity: DA
    type: NN
    modes:
      label: z
      range: [0,20]
      steps: 200
    n_traits:
      n_hidden: [ 512, 512, 512, 512 ]
    training:
      validation_split: 0.1
      learning_rates: [ 1.e-2, 1.e-4, 1.e-6 ]
      batch_sizes: [ 1000, 1000, 1000 ]
      gradient_accumulation_steps: [ 1, 1, 1 ]
      patience_values: [ 25, 25, 25 ]
      max_epochs: [ 1000, 1000, 1000 ]
